#!/bin/bash

# Check if a filename was provided
if [ -z "$1" ]; then
    echo "Usage: run <filename.py>"
    exit 1
fi

# Activate virtual environment
source ~/Downloads/MedicalVolumeRenderer/.mvr/bin/activate

# Set PYTHONPATH to include the build folder
export PYTHONPATH=$PYTHONPATH:/home/akashmaji/Downloads/MedicalVolumeRenderer/build

# Run the Python script
python3 "$1"
